In [1]:
#Q1
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
add_arr = arr + 2
mult_arr = arr * 3
div_arr = arr / 2

print("Original Array:", arr)
print("After Addition:", add_arr)
print("After Multiplication:", mult_arr)
print("After Division:", div_arr)


Original Array: [1 2 3 4 5]
After Addition: [3 4 5 6 7]
After Multiplication: [ 3  6  9 12 15]
After Division: [0.5 1.  1.5 2.  2.5]


In [6]:
#Q2
arr = np.array([1, 2, 3, 4, 5])
import numpy as np
res = np.flip(arr)

print("(a) Final reversed array: ", res)
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
def most_frequent(arr):
    unique, counts = np.unique(arr, return_counts=True)
    most_freq = unique[np.argmax(counts)]
    indices = np.where(arr == most_freq)[0]
    return most_freq, indices
freq_x, indices_x = most_frequent(x)
freq_y, indices_y = most_frequent(y)
print("(b)");
print("(i) Most Frequent in x:", freq_x, "at indices", indices_x)
print("(ii) Most Frequent in y:", freq_y, "at indices", indices_y)


(a) Final reversed array:  [5 4 3 2 1]
(b)
(i) Most Frequent in x: 1 at indices [0 5 7 8 9]
(ii) Most Frequent in y: 1 at indices [0 1 2]


In [8]:
#Q3
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
element1 = arr[0, 1]
element2 = arr[2, 0]

print("(a) Element at (1st row, 2nd column):", element1)
print("(b) Element at (3rd row, 1st column):", element2)


(a) Element at (1st row, 2nd column): 20
(b) Element at (3rd row, 1st column): 70


In [11]:
#Q4
gagan = np.linspace(10, 100, 25)


print("Array:", gagan)
print("Dimensions:", gagan.ndim)
print("Shape:", gagan.shape)
print("Total Elements:", gagan.size)
print("Data Type of Elements:", gagan.dtype)
print("Total Bytes Consumed:", gagan.nbytes)

gagan_transposed = gagan.reshape(25, 1)
print("\nTransposed using reshape():\n", gagan_transposed)


gagan_t = gagan.T  
print("\nTransposed using T attribute:", gagan_t)
print("Shape after T attribute:", gagan_t.shape)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type of Elements: float64
Total Bytes Consumed: 200

Transposed using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transposed using T attribute: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Shape after T attribute: (25,)


In [12]:
#Q5
ucs420_Gagan = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])

print("\nMean:", np.mean(ucs420_Gagan))
print("Median:", np.median(ucs420_Gagan))
print("Max:", np.max(ucs420_Gagan))
print("Min:", np.min(ucs420_Gagan))
print("Unique Elements:", np.unique(ucs420_Gagan))

reshaped_ucs420_Gagan = ucs420_Gagan.reshape(4, 3)
print("\nReshaped Array (4x3):\n", reshaped_ucs420_Gagan)


resized_ucs420_Gagan = np.resize(ucs420_Gagan, (2, 3))
print("\nResized Array (2x3):\n", resized_ucs420_Gagan)



Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array (2x3):
 [[10 20 30]
 [40 50 60]]
